# Generated by Django 5.2.17 on 2026-10-03 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier or SVG symbol', max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source_url', models.URLField(max_length=1000)),
                ('application_url', models.URLField(db_index=True, max_length=1000)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('opportunity_type', models.CharField(choices=[('internship', 'Internship'), ('full-time', 'Full-time'), ('part-time', 'Part-time'), ('apprenticeship', 'Apprenticeship'), ('graduate-program', 'Graduate Program'), ('trainee', 'Trainee'), ('contract', 'Contract')], db_index=True, default='internship', max_length=30)),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher'), ('0-1', '0-1 years'), ('1-2', '1-2 years'), ('2+', '2+ years')], db_index=True, default='fresher', max_length=20)),
                ('remote_type', models.CharField(choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], db_index=True, default='on-site', max_length=20)),
                ('location_name', models.CharField(db_index=True, max_length=150)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=10)),
                ('is_salary_disclosed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('closing-soon', 'Closing Soon'), ('expired', 'Expired'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('pending-review', 'Pending Review'), ('reported', 'Reported'), ('unverified', 'Unverified')], db_index=True, default='verified', max_length=20)),
                ('posted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('application_open_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='sources.jobsource')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='jobs.category')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_jobs', to='jobs.skill')),
            ],
            options={
                'verbose_name': 'Job Skill',
                'verbose_name_plural': 'Job Skills',
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', through='jobs.JobSkill', to='jobs.skill'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'opportunity_type', 'experience_level'], name='jobs_job_status_105b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'application_deadline'], name='jobs_job_status_e53abc_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'title'], name='jobs_job_company_b040c8_idx'),
        ),
    ]
