# Generated by Django 5.2.17 on 2026-10-03 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source_type', models.CharField(choices=[('official_company', 'Official Company Careers Page'), ('government', 'Official Government Portal'), ('authorized_api', 'Authorized API'), ('rss_feed', 'RSS / Atom Feed'), ('job_board', 'Job Board / Aggregator'), ('manual_admin', 'Manual Admin Entry')], default='official_company', max_length=50)),
                ('source_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('failing', 'Failing'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_verified', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('total_jobs_collected', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Job Source',
                'verbose_name_plural': 'Job Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('warning', 'Warning'), ('failed', 'Failed')], default='started', max_length=20)),
                ('items_fetched', models.PositiveIntegerField(default=0)),
                ('items_created', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_skipped', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_logs', to='sources.jobsource')),
            ],
            options={
                'verbose_name': 'Scraping Log',
                'verbose_name_plural': 'Scraping Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
