# Generated by Django 5.2.17 on 2026-10-03 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_savedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('suspicious_link', 'Suspicious or Broken Application Link'), ('requesting_money', 'Opportunity is Requesting Money / Application Fee'), ('incorrect_information', 'Inaccurate Job Details or Deadlines'), ('expired_opportunity', 'Opportunity Has Already Closed or Expired'), ('fake_company', 'Suspected Fraudulent or Impersonated Employer'), ('duplicate_listing', 'Duplicate Opportunity Listing'), ('other', 'Other Issue')], default='suspicious_link', max_length=50)),
                ('details', models.TextField(help_text='Please describe why this listing is suspicious or inaccurate.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Investigating'), ('resolved', 'Resolved (Action Taken)'), ('dismissed', 'Dismissed (Valid Listing)')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal moderation notes.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing Report',
                'verbose_name_plural': 'Listing Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
