# Generated by Django 5.2.17 on 2026-10-03 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Fresher Python Backend Roles', max_length=150)),
                ('keywords', models.CharField(blank=True, help_text='e.g. Python, Django, AWS', max_length=255)),
                ('location', models.CharField(blank=True, help_text='e.g. Bangalore or Remote', max_length=150)),
                ('opportunity_type', models.CharField(blank=True, max_length=30)),
                ('experience_level', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='daily', max_length=20)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Alert',
                'verbose_name_plural': 'Job Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('job_alert', 'New Matching Opportunity'), ('deadline_approaching', 'Saved Opportunity Deadline'), ('application_status', 'Application Progress Reminder'), ('system', 'System Notice')], default='system', max_length=30)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
